{% set name = "upsonic" %}
{% set version = "0.28.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/upsonic-{{ version }}.tar.gz
  sha256: 6d4c4df2c4bab83e9612c443a7548e4a6ac6423428678091f92afcf6e8aa496a

build:
  entry_points:
    - upsonic=upsonic.remote.interface:Upsonic_CLI
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - fire ==0.5.0mgzip,==0.2.1rich,>=13.5.2cryptography,==41.0.3dill,==0.3.8requestspython-dotenv,==1.0.0cloudpickle,==3.0.0memory-profiler,==0.61.0langchain_openai
    - mgzip =0.2.1
    - rich >=13.5.2
    - cryptography =41.0.3
    - dill =0.3.8
    - requests =2.28.2
    - python-dotenv =1.0.0
    - cloudpickle =3.0.0
    - memory_profiler =0.61.0
    - langchain-openai

test:
  imports:
    - upsonic
  commands:
    - pip check
    - upsonic --help
  requires:
    - pip

about:
  home: https://github.com/Upsonic/Upsonic
  summary: Magic Cloud Layer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
