{% set name = "upsonic" %}
{% set version = "0.34.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/upsonic-{{ version }}.tar.gz
  sha256: 661bfb10d9c93ecd12325a1787479b6a9c67131c1a06166ec770ff7fe9a8a714

build:
  entry_points:
    - upsonic=upsonic.remote.interface:Upsonic_CLI
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - fire =0.5.0
    - mgzip =0.2.1
    - cryptography =40.0.2
    - dill
    - requests
    - python-dotenv
    - cloudpickle
    - memory_profiler =0.61.0
    - colorama
    - termcolor

test:
  imports:
    - upsonic
  commands:
    - pip check
    - upsonic --help
  requires:
    - pip

about:
  home: https://github.com/Upsonic/Upsonic
  summary: Magic Cloud Layer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
